name: Mário Salimon
favicon: null
layout_spectrum: 0.22951129730790854
typography_spectrum: 0.06200255476869643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9253180685918778
  lightness: 0.1745167823974043
  saturation: 0.16640885453671217
  rhythmicContrast: 0.6227836138568819
purpose: []
