name: Mário Salimon
favicon: null
layout_spectrum: 0.05262
typography_spectrum: 0.06200255476869643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
